name: test
on:
  push:
    branches: ["next-js-migration"]
  pull_request:
    branches: ["next-js-migration"]

jobs:
  run-jest-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: latest
        - run: |
            npm ci 
            npm run test:ci